### ISSUE TITLE
Can I use it on Linux?

### ISSUE THREAD

**Issue by moooep** [pdbme/pdbMate#4]
Hey! 

I am wondering it is usable on Linux?

**Comment by pdbme** [comment]
You can use it on linux but you need to install the dotnet6 runtime first (this is also the case for windows).

Please download the latest v0.2 release for linux-x64 and install dotnet6 runtime

Microsoft explains it here:

https://docs.microsoft.com/en-us/dotnet/core/install/linux?WT.mc_id=dotnet-35129-website

If you run into any problems please let me know and provide more details (linux distro etc). I only tested windows so far but can easily setup a docker image to do testing for linux.

Please also read the updated readme here on github for details infos on how to use pdbMate.

**Comment by nexalapp** [comment]
Hello @pdbme, 

I am trying to use the tool on linux and have followed the instructions you've posted above:

- I have downloaded the latest v0.2 release for linux-x64
- I have setup the most recent version of dotnet (v6.x) using the link provided above. 
- I have setup my appsettings.json adding in my pdbAPI key, my downloader credentials, SourceFolders pointing to my download directory, and TargetFolder pointing to directory my media manager reads from.

After performing these steps, I don't get an error  when I run `pdbMate rename --dryrun`. However there is also no output even when I manually move some videos into the SourceFolder location. 

I have also tried `pdbMate autopilot` but this gives the error attached below:
```
[11:49:10 ERR] Exception when executing Application.
System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.List`1[pdbMate.Core.Data.Sabnzbd.SabnzbdSlotAction]. Path: $.history.slots[0].stage_log | LineNumber: 0 | BytePositionInLine: 612.
   at RestSharp.RestClient.ThrowIfError(RestResponse response)
   at RestSharp.RestClientExtensions.GetAsync[T](RestClient client, RestRequest request, CancellationToken cancellationToken)
   at pdbMate.Core.SabnzbdService.GetHistory(Int32 start, Int32 limit) in C:\Users\steve\Documents\GitHub\pdbmate\src\pdbMate.Core\SabnzbdService.cs:line 105
   at pdbMate.Core.UsenetDownloadService.GetReleasesToExcludeFromSabnzbd(List`1 releases) in C:\Users\steve\Documents\GitHub\pdbmate\src\pdbMate.Core\UsenetDownloadService.cs:line 206
   at pdbMate.Core.UsenetDownloadService.GetReleasesToExcludeFromDownloadClient(List`1 resultList, DownloadClient client) in C:\Users\steve\Documents\GitHub\pdbmate\src\pdbMate.Core\UsenetDownloadService.cs:line 179
   at pdbMate.Core.UsenetDownloadService.Execute(Boolean dryRun, DownloadClient client)
   at pdbMate.Core.Application.Autopilot(Boolean dryRun, String client) in C:\Users\steve\Documents\GitHub\pdbmate\src\pdbMate.Core\Application.cs:line 58
   at pdbMate.Program.RunApp(String[] args, BaseOptions options, AppAction action) in C:\Users\steve\Documents\GitHub\pdbmate\src\pdbMate\Program.cs:line 88
```

One thing that did seem odd to me was that the error messages seems to point to files located on someone else's windows machine: `C:\Users\steve\Documents\`. Could this possibly be the cause of the error message?

I would love to help debug this with you, so please let me know what additional information I can provide that would be helpful. Thank you!

**Comment by pdbme** [comment]
Hello @nexalapp,

when you run autopilot mode it means pdbMate tries to connect to your sabnzbd or nzbget depending on your settings. So if you did not set your usenet downloader in the appsettings.json this will not work.

Your first try with the rename option should be the way to go. Since there is no error message, it would help to get a look at your appsettings.json and the files in your source directory. Please anonymize any apikeys before posting screenshots here.

Error message pointing to `C:\Users\steve\Documents\` are not the issue. This is due to the machine where the application was compiled.

**Comment by nexalapp** [comment]
My apologies, I failed to mention that I did also have a downloader set up in the config file. You can see my `appsettings.json` file with API keys omitted below:
```
{
  "Rename": {
    "FilenameTemplate": "{Video.ReleasedateShort} - {Video.Title} - {VideoQuality.SimplifiedName} - {PdbId}{FileExtension}",
    "FolderTemplate": "{Video.Site.Sitename}",
    "SourceFolders": [
      "/share/Downloads/completed/Videos"
    ],
    "TargetFolder": "/share/Media/Videos/Collections/"
  },
  "PdbApi": {
    "BaseUrl": "https://api.porndb.me/",
    "ApiKey": "<API-Key-Omitted>"
  },
  "Nzbget": {
    "Hostname": "127.0.0.1",
    "Port": 6789,
    "Username": "",
    "Password": "",
    "UseHttps": false
  },
  "Sabnzbd": {
    "Url": "http://mini.local:8080/sabnzbd/api",
    "ApiKey": "<API-Key-Omitted>"
  },
  "UsenetDownload": {
    "AllowedQualities": [ "1080p", "2160p" ],
    "KeepOnlyHighestQuality": true,
    "DownloadFavoriteActors": true,
    "DownloadFavoriteSites": true
  }
}
```
I only use sabnzbd. Could it be because I need to remove the empty nzbget dictionary from the JSON file? Or maybe I need to use the IP address of the download machine instead of its '.local' address?

So far I've only copied a few videos into the root of the source directory. Does the tool assume that each video will be in its own directory?

I will try out some of these ideas and report back with any progress.

**Comment by nexalapp** [comment]
I have tried using the IP address of the machine running sabnzbd (instead of '.local' address) and I also put each  video in own directory in the source folder. When I re-ran the two commands neither had any output. Is this normal? Or how would I tell that the tool is working? 

I have copied the shell session for your evaluation below:
```
root@pdbmate:/usr/src/app# ./pdbMate rename --dryrun
root@pdbmate:/usr/src/app# ./pdbMate autopilot
root@pdbmate:/usr/src/app# 
```

**Comment by pdbme** [comment]
Your appsettings.json seems to be correct. Nzbget and sabnzbd can be used both in the settings.

Please use the `--verbose` option to get more logs in your command line and lets focus on the `rename --dryrun` first before moving on to autopilot.

**Comment by nexalapp** [comment]
Thank you. Adding `--verbose` gave me a clue. It looks like to rename the script has to match the video file to a record in the database. The random files I had selected were from 2016 and it looks like the database only goes as far back as 2018. When I tried again with files from 2019 they were able to be identified and renamed successfully. 

I am currently in the process of sending each of my series through the renamer function. Once completed, I will then move on to the `autopilot` function also using the `--verboase` flag.

**Comment by nexalapp** [comment]
Success! I can confirm that the auto-pilot function does work. 

However, I have noticed that after the downloads have been sent to the download client, the script exits without any error messages. I assume this is intentional. However, I am curious what the expectation is for a completely hands-off setup. Should I be looking to setup a cron job that will kick off this autopilot function daily?
