### ISSUE TITLE
Unhandled exception. System.IO.InvalidDataException: Failed to load configuration from file

### ISSUE THREAD

**Issue by Thornic** [pdbme/pdbMate#7]
Any idea what goes wrong?

```
s:\pdbMate2>pdbMate rename --dryrun
Unhandled exception. System.IO.InvalidDataException: Failed to load configuration from file 's:\pdbMate2\appsettings.json'.
 ---> System.FormatException: Could not parse the JSON file.
 ---> System.Text.Json.JsonReaderException: 'D' is an invalid escapable character within a JSON string. The string should be correctly escaped. LineNumber: 5 | BytePositionInLine: 10.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 data, Int32 idx)
   at System.Text.Json.Utf8JsonReader.ConsumeString()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at pdbMate.Program.RunApp(String[] args, BaseOptions options, AppAction action) in C:\Users\steve\Documents\GitHub\pdbmate\src\pdbMate\Program.cs:line 31
   at pdbMate.Program.<>c__DisplayClass1_0.<Main>b__0(RenameOptions opts) in C:\Users\steve\Documents\GitHub\pdbmate\src\pdbMate\Program.cs:line 22
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 notParsedFunc)
   at pdbMate.Program.Main(String[] args) in C:\Users\steve\Documents\GitHub\pdbmate\src\pdbMate\Program.cs:line 20
```

**Comment by pdbme** [comment]
Something in your appsettings.json is wrong and can't be parsed.

Please download newest version v0.3 and run interactive setup (remove your appsettings.json) and run pdbMate without any command line arguments.

The setup progress then asks you all the stuff that needs to be configured and in the end generates an appsettings.json file. The setup has advanced validation in place so you have a good chance of generating a valid json file.
